#!/usr/bin/env node
var validateSchema = require('./validateSchema');
var argv = require('yargs')
    .usage('$0 [--version <version>] <catalog.json> [<anothercatalog.json> ...]')
    .describe('version', 'Version of schema to validate against (master, x.y.z)')
    .default('version', validateSchema.defaultVersion)
    .describe('terriajsdir', 'Directory containing TerriaJS, to deduce version automatically.')
    .describe('quiet', 'Suppress non-error output.')
    .boolean('quiet')
    .describe('schemadir', 'Path to the exact schema dir, to skip all schema detection logic.')
    .demand(1)
    .help('help')
    .argv;

argv.catalogFile = argv._[0];

validateSchema(argv);